//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Detail
    {
        public int Id_OrderDetail { get; set; }
        public Nullable<int> Id_Order { get; set; }
        public Nullable<int> Id_Product { get; set; }
        public Nullable<int> Id_Rate { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> Delete_Stt { get; set; }
    }
}
