//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Order { get; set; }
        public Nullable<int> Id_User { get; set; }
        public Nullable<int> Id_Discount { get; set; }
        public Nullable<int> Id_Payment { get; set; }
        public Nullable<int> Status { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<double> Total_Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<bool> Delete_Stt { get; set; }
    }
}
