//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id_Product { get; set; }
        public Nullable<int> Id_Category { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Discount { get; set; }
        public string Photo { get; set; }
        public string Note { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Id_Color { get; set; }
        public Nullable<int> Id_Size { get; set; }
        public Nullable<bool> Delete_Stt { get; set; }
    }
}
